# Generated by Django 5.0.3 on 2024-03-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Название'),
        ),
    ]
